stages:          # List of stages for jobs, and their order of execution
  - setup
  - build
  - test
  - deploy

before_script: ## Check this part

  - export http_proxy=http://proxy.eu.novartis.net:2010/
  - export https_proxy=http://proxy.eu.novartis.net:2010/
  - export NOT_CRAN=true
  - export CCACHE_DIR=/tmp
  - export PATH=/usr/lib/ccache:$PATH


# <DON'T REMOVE!>
variables:
  RENV_PATHS_CACHE: "~/.renv/cache"
  RENV_PATHS_LIBRARY_ROOT: "~/.renv/library"

# <DON'T REMOVE!>
cache:
  key: ${CI_JOB_NAME}
  paths:
    - ${RENV_PATHS_CACHE}
    - ${RENV_PATHS_LIBRARY}

Setup:
  stage: setup
  script:
    - >
      if [ ! -d "$RENV_PATHS_CACHE" ]; then
        mkdir -p $RENV_PATHS_CACHE;
        echo "Installing RENV_PATHS_CACHE in ${RENV_PATHS_CACHE}...";
      fi
    - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv');"
    - Rscript -e "renv::restore();"

Build:
  stage: build
  script:
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1) && echo ${PKG_FILE_NAME}
    - mv "${PKG_FILE_NAME}" monitOS-source-fast.tar.gz
  artifacts:
    name: "build-fast"
    expire_in: 1 day
    paths:
       - monitOS-source-fast.tar.gz

Check:
  stage: test
  script:
    - tar xf "monitOS-source-fast.tar.gz"
    - export NOT_CRAN=false
    - R CMD check monitOS --no-build-vignettes --no-manual
    - rm -rf monitOS.Rcheck/monitOS
  artifacts:
    name: "Rcheck-${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    expire_in: 1 week
    paths:
      - monitOS.Rcheck/

Deploy:
  stage: deploy
  only:
    - main
  script:
    - R CMD build . --as-cran
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1) && echo ${PKG_FILE_NAME}
    - mv "${PKG_FILE_NAME}" monitOS-source.tar.gz
    - R -e 'source("deploy/deploy-workflow.R"); deploy_app_rsc()'
  dependencies: []
  artifacts:
    name: "monitOS_source"
    expire_in: 1 month
    paths:
      - monitOS-source.tar.gz

