repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: check-case-conflict
      - id: check-added-large-files
        args: ["--maxkb=1000", "--enforce-all"]
      - id: detect-private-key


# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3.9009
    hooks:
    -   id: use-tidy-description
    -   id: lintr
        verbose: true
        files: ^(R/).*\.(R|r|Rmd|rmd)$
        exclude: ^R/(ui\.R|server\.R|runApp\.R)$
    -   id: readme-rmd-rendered
    -   id: no-browser-statement
    -   id: pkgdown

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: ["--write-changes"]  # Automatically fix spelling errors if only one suggestion
        files: ^.*\.(R|md|Rmd)$  # Only apply to R and Markdown files

ci:
    autoupdate_schedule: monthly
    skip: [pkgdown]
