# Generated by tools/build_shinylive.R. Do not edit by hand.

library(bslib)
library(shiny)

source("R/posteriors.R", local = TRUE)
source("R/probs.R", local = TRUE)
source("R/bounds.R", local = TRUE)
source("R/ui.R", local = TRUE)
source("R/server.R", local = TRUE)

ui <- app_ui()
server <- app_server

shinyApp(ui, server)
