#!/usr/bin/env Rscript

args <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("^--file=", args, value = TRUE)
script_path <- if (length(file_arg)) {
  normalizePath(sub("^--file=", "", file_arg[1]), mustWork = TRUE)
} else {
  normalizePath("tools/build_shinylive.R", mustWork = TRUE)
}

repo_root <- dirname(dirname(script_path))
app_dir <- file.path(repo_root, "inst", "shinylive-app")
app_r_dir <- file.path(app_dir, "R")
docs_dir <- file.path(repo_root, "docs", "shinylive-app")

dir.create(app_r_dir, recursive = TRUE, showWarnings = FALSE)

shared_files <- c("posteriors.R", "probs.R", "bounds.R", "ui.R", "server.R")
file.copy(
  from = file.path(repo_root, "R", shared_files),
  to = file.path(app_r_dir, shared_files),
  overwrite = TRUE
)

logo_src <- paste0(
  "data:image/png;base64,",
  base64enc::base64encode(file.path(app_dir, "logo.png"))
)

logo_data_path <- file.path(app_r_dir, "logo_data.R")
writeLines(
  c(
    "# Generated by tools/build_shinylive.R. Do not edit by hand.",
    sprintf('logo_src <- "%s"', logo_src)
  ),
  logo_data_path
)

wrapper_lines <- c(
  "# Generated by tools/build_shinylive.R. Do not edit by hand.",
  "",
  "library(bslib)",
  "library(shiny)",
  "",
  'source("R/logo_data.R", local = TRUE)',
  'source("R/posteriors.R", local = TRUE)',
  'source("R/probs.R", local = TRUE)',
  'source("R/bounds.R", local = TRUE)',
  'source("R/ui.R", local = TRUE)',
  'source("R/server.R", local = TRUE)',
  "",
  "ui <- app_ui(logo_src = logo_src, register_resources = FALSE)",
  "server <- app_server",
  "",
  "shinyApp(ui, server)"
)

wrapper_path <- file.path(app_dir, "app.R")
writeLines(wrapper_lines, wrapper_path)

app_files <- c(
  "app.R",
  file.path("R", c("logo_data.R", shared_files))
)

app_json <- lapply(app_files, function(rel_path) {
  list(
    name = rel_path,
    content = paste(readLines(file.path(app_dir, rel_path), warn = FALSE), collapse = "\n"),
    type = "text"
  )
})

dir.create(docs_dir, recursive = TRUE, showWarnings = FALSE)
jsonlite::write_json(
  app_json,
  path = file.path(docs_dir, "app.json"),
  auto_unbox = TRUE,
  pretty = FALSE
)

message("Shinylive wrapper regenerated in ", app_dir)
message("Published app manifest regenerated in ", file.path(docs_dir, "app.json"))
