// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mod2
double mod2(double a);
RcppExport SEXP _monitOS_mod2(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(mod2(a));
    return rcpp_result_gen;
END_RCPP
}
// sum_sug
double sum_sug(NumericVector x);
RcppExport SEXP _monitOS_sum_sug(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(sum_sug(x));
    return rcpp_result_gen;
END_RCPP
}
// exactt
double exactt(double events, double n0, double n1, double crit, double hr);
RcppExport SEXP _monitOS_exactt(SEXP eventsSEXP, SEXP n0SEXP, SEXP n1SEXP, SEXP critSEXP, SEXP hrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type events(eventsSEXP);
    Rcpp::traits::input_parameter< double >::type n0(n0SEXP);
    Rcpp::traits::input_parameter< double >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< double >::type crit(critSEXP);
    Rcpp::traits::input_parameter< double >::type hr(hrSEXP);
    rcpp_result_gen = Rcpp::wrap(exactt(events, n0, n1, crit, hr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_monitOS_mod2", (DL_FUNC) &_monitOS_mod2, 1},
    {"_monitOS_sum_sug", (DL_FUNC) &_monitOS_sum_sug, 1},
    {"_monitOS_exactt", (DL_FUNC) &_monitOS_exactt, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_monitOS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
