# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mod2 <- function(a) {
    .Call(`_monitOS_mod2`, a)
}

sum_sug <- function(x) {
    .Call(`_monitOS_sum_sug`, x)
}

exactt <- function(events, n0, n1, crit, hr) {
    .Call(`_monitOS_exactt`, events, n0, n1, crit, hr)
}

